services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=musala
    - POSTGRES_PASSWORD=musala123
    - POSTGRES_DB=postgres
  app:
    build: ./
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres